// ESLint flat config for the Svelte 5 + TypeScript frontend.
//
// Scoped to correctness, not formatting: no stylistic rules, no Prettier. The
// components in this project are hand-formatted in ways that read better than
// a formatter would produce (aligned option tables, deliberately wrapped
// comments), and reflowing them would cost more than it buys.
//
// Run:  npm run lint        (report)
//       npm run lint:fix    (apply the fixable ones)

import js from '@eslint/js'
import globals from 'globals'
import svelte from 'eslint-plugin-svelte'
import ts from 'typescript-eslint'
import svelteConfig from './svelte.config.js'

export default ts.config(
  {
    // Generated or built output. wailsjs/ is regenerated by `wails build` on
    // every run, so linting it would only ever produce noise we can't fix.
    ignores: ['dist/', 'wailsjs/', 'node_modules/'],
  },

  js.configs.recommended,
  ...ts.configs.recommended,
  ...svelte.configs.recommended,

  {
    languageOptions: {
      globals: { ...globals.browser },
    },
    rules: {
      // Underscore-prefixed bindings are the conventional "I know, I meant to
      // ignore this" marker — most often a destructured value or a caught
      // error we don't inspect.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrors: 'none',
        },
      ],
    },
  },

  {
    files: ['**/*.svelte', '**/*.svelte.ts'],
    languageOptions: {
      parserOptions: {
        // Lets the Svelte parser hand <script lang="ts"> blocks to
        // typescript-eslint, and resolves runes ($state, $derived, …) against
        // the real Svelte config rather than guessing.
        parser: ts.parser,
        svelteConfig,
      },
    },
    rules: {
      // Surface Svelte compiler warnings (unused CSS selectors, invalid
      // bindings, a11y complaints) as lint failures so CI sees what the dev
      // server would only print in passing.
      'svelte/valid-compile': 'error',
    },
  },

  {
    // Config files run in Node, not the browser.
    files: ['*.config.js', '*.config.ts'],
    languageOptions: {
      globals: { ...globals.node },
    },
  }
)
