// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDownloadFolder() {
  return window['go']['main']['App']['ChooseDownloadFolder']();
}

export function DownloadVideo(arg1) {
  return window['go']['main']['App']['DownloadVideo'](arg1);
}

export function DownloadsFolder() {
  return window['go']['main']['App']['DownloadsFolder']();
}

export function FfmpegAvailable() {
  return window['go']['main']['App']['FfmpegAvailable']();
}

export function GetDepsStatus() {
  return window['go']['main']['App']['GetDepsStatus']();
}

export function GetPreview(arg1) {
  return window['go']['main']['App']['GetPreview'](arg1);
}

export function InstallExtras() {
  return window['go']['main']['App']['InstallExtras']();
}

export function InstallFfmpeg() {
  return window['go']['main']['App']['InstallFfmpeg']();
}

export function InstallPython() {
  return window['go']['main']['App']['InstallPython']();
}

export function InstallYtDlp() {
  return window['go']['main']['App']['InstallYtDlp']();
}

export function InstallYtDlpZip() {
  return window['go']['main']['App']['InstallYtDlpZip']();
}

export function ListFormats(arg1) {
  return window['go']['main']['App']['ListFormats'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OpenDependenciesFolder() {
  return window['go']['main']['App']['OpenDependenciesFolder']();
}

export function PreviewPort() {
  return window['go']['main']['App']['PreviewPort']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SkipFfmpeg() {
  return window['go']['main']['App']['SkipFfmpeg']();
}

export function YtDlpInstalled() {
  return window['go']['main']['App']['YtDlpInstalled']();
}

export function YtDlpVersion() {
  return window['go']['main']['App']['YtDlpVersion']();
}
