// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadVideo(arg1) {
  return window['go']['main']['App']['DownloadVideo'](arg1);
}

export function InstallYtDlp() {
  return window['go']['main']['App']['InstallYtDlp']();
}

export function YtDlpInstalled() {
  return window['go']['main']['App']['YtDlpInstalled']();
}

export function YtDlpVersion() {
  return window['go']['main']['App']['YtDlpVersion']();
}
