// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseDownloadFolder():Promise<string>;

export function DownloadVideo(arg1:main.DownloadOptions):Promise<string>;

export function DownloadsFolder():Promise<string>;

export function FfmpegAvailable():Promise<boolean>;

export function GetDepsStatus():Promise<main.DepsStatus>;

export function GetPreview(arg1:string):Promise<main.PreviewInfo>;

export function InstallExtras():Promise<void>;

export function InstallFfmpeg():Promise<void>;

export function InstallPython():Promise<void>;

export function InstallYtDlp():Promise<string>;

export function InstallYtDlpZip():Promise<void>;

export function ListFormats(arg1:string):Promise<main.FormatList>;

export function LoadSettings():Promise<string>;

export function OpenDependenciesFolder():Promise<void>;

export function PreviewPort():Promise<number>;

export function SaveSettings(arg1:string):Promise<void>;

export function SkipFfmpeg():Promise<void>;

export function YtDlpInstalled():Promise<boolean>;

export function YtDlpVersion():Promise<string>;
