// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadVideo(arg1:string):Promise<string>;

export function InstallYtDlp():Promise<string>;

export function YtDlpInstalled():Promise<boolean>;

export function YtDlpVersion():Promise<string>;
